Name:           bluej
Version:        5.0.3
Release:        1%{?dist}
Summary:        A free Java Development Environment

License:        GPLv2+
URL:            https://www.bluej.org/
Source0:        https://github.com/NikolajK-HTX/bluej-spec/releases/download/v%{version}/%{name}-%{version}.tar.gz

Requires:       java-11-openjdk-devel
Requires:       java-11-openjdk-jmods
Requires:       openjfx

%description
A free Java Development Environment designed for beginners, 
used by millions worldwide.

%prep
%autosetup

%install
rm -rf $RPM_BUILD_ROOT
find examples -type f -exec install -Dm 644 "{}" "%{buildroot}/opt/%{name}/examples/{}" \;
find icons -type f -exec install -Dm 644 "{}" "%{buildroot}/opt/%{name}/icons/{}" \;
find lib -type f -exec install -Dm 644 "{}" "%{buildroot}/opt/%{name}/lib/{}" \;

install -Dm 0755 bluej                 %{buildroot}/opt/%{name}/bluej
install -Dm 0644 LICENSE.txt           %{buildroot}/opt/%{name}/LICENSE.txt
install -Dm 0644 README.TXT            %{buildroot}/opt/%{name}/README.txt
install -Dm 0644 THIRDPARTYLICENSE.txt %{buildroot}/opt/%{name}/THIRDPARTYLICENSE.txt

install -Dm 0664 bluej.desktop         %{buildroot}/usr/share/applications/bluej.desktop

%post
ln -s /usr/lib/jvm/openjfx/ /usr/lib/jvm/openjfx/lib

%files
%license LICENSE.txt
%doc README.TXT
%dir /opt/%{name}/
/opt/%{name}/bluej
/opt/%{name}/LICENSE.txt
/opt/%{name}/README.txt
/opt/%{name}/THIRDPARTYLICENSE.txt
/opt/%{name}/examples/examples/debugdemo/Car.java
/opt/%{name}/examples/examples/debugdemo/Demo.java
/opt/%{name}/examples/examples/debugdemo/README.TXT
/opt/%{name}/examples/examples/debugdemo/package.bluej
/opt/%{name}/examples/examples/file-reader/FileReader.java
/opt/%{name}/examples/examples/file-reader/README.TXT
/opt/%{name}/examples/examples/file-reader/package.bluej
/opt/%{name}/examples/examples/file-reader/test.txt
/opt/%{name}/examples/examples/hello/Hello.java
/opt/%{name}/examples/examples/hello/README.TXT
/opt/%{name}/examples/examples/hello/package.bluej
/opt/%{name}/examples/examples/people/Database.ctxt
/opt/%{name}/examples/examples/people/Database.java
/opt/%{name}/examples/examples/people/Person.ctxt
/opt/%{name}/examples/examples/people/Person.java
/opt/%{name}/examples/examples/people/README.TXT
/opt/%{name}/examples/examples/people/Staff.ctxt
/opt/%{name}/examples/examples/people/Staff.java
/opt/%{name}/examples/examples/people/Student.ctxt
/opt/%{name}/examples/examples/people/Student.java
/opt/%{name}/examples/examples/people/package.bluej
/opt/%{name}/examples/examples/people2/Address.java
/opt/%{name}/examples/examples/people2/Database.java
/opt/%{name}/examples/examples/people2/Person.java
/opt/%{name}/examples/examples/people2/README.TXT
/opt/%{name}/examples/examples/people2/Staff.java
/opt/%{name}/examples/examples/people2/Student.java
/opt/%{name}/examples/examples/people2/package.bluej
/opt/%{name}/examples/examples/picture/Canvas.java
/opt/%{name}/examples/examples/picture/Circle.java
/opt/%{name}/examples/examples/picture/Picture.java
/opt/%{name}/examples/examples/picture/README.TXT
/opt/%{name}/examples/examples/picture/Square.java
/opt/%{name}/examples/examples/picture/Triangle.java
/opt/%{name}/examples/examples/picture/package.bluej
/opt/%{name}/examples/examples/shapes/Canvas.java
/opt/%{name}/examples/examples/shapes/Circle.java
/opt/%{name}/examples/examples/shapes/README.TXT
/opt/%{name}/examples/examples/shapes/Square.java
/opt/%{name}/examples/examples/shapes/Triangle.java
/opt/%{name}/examples/examples/shapes/package.bluej
/opt/%{name}/icons/icons/bluej-84-toned.jpg
/opt/%{name}/icons/icons/bluej-icon-512-embossed.png
/opt/%{name}/icons/icons/bluej-vista.ico
/opt/%{name}/icons/icons/license.txt
/opt/%{name}/lib/lib/afrikaans/dialogues
/opt/%{name}/lib/lib/afrikaans/labels
/opt/%{name}/lib/lib/afrikaans/moe.help
/opt/%{name}/lib/lib/afrikaans/templates/LEESMY.txt
/opt/%{name}/lib/lib/afrikaans/templates/html.tmpl
/opt/%{name}/lib/lib/afrikaans/templates/method.tmpl
/opt/%{name}/lib/lib/afrikaans/templates/newclass/LEESMY.txt
/opt/%{name}/lib/lib/afrikaans/templates/newclass/abstract.tmpl
/opt/%{name}/lib/lib/afrikaans/templates/newclass/enum.tmpl
/opt/%{name}/lib/lib/afrikaans/templates/newclass/interface.tmpl
/opt/%{name}/lib/lib/afrikaans/templates/newclass/stdclass.tmpl
/opt/%{name}/lib/lib/afrikaans/templates/newclass/unittest.tmpl
/opt/%{name}/lib/lib/afrikaans/templates/readme.tmpl
/opt/%{name}/lib/lib/bluej.defs
/opt/%{name}/lib/lib/bluej.jar
/opt/%{name}/lib/lib/bluejcore.jar
/opt/%{name}/lib/lib/bluejeditor.jar
/opt/%{name}/lib/lib/bluejext2.jar
/opt/%{name}/lib/lib/catalan/dialogues
/opt/%{name}/lib/lib/catalan/labels
/opt/%{name}/lib/lib/catalan/moe.help
/opt/%{name}/lib/lib/catalan/templates/README
/opt/%{name}/lib/lib/catalan/templates/html.tmpl
/opt/%{name}/lib/lib/catalan/templates/method.tmpl
/opt/%{name}/lib/lib/catalan/templates/newclass/README
/opt/%{name}/lib/lib/catalan/templates/newclass/abstract.tmpl
/opt/%{name}/lib/lib/catalan/templates/newclass/enum.tmpl
/opt/%{name}/lib/lib/catalan/templates/newclass/interface.tmpl
/opt/%{name}/lib/lib/catalan/templates/newclass/stdclass.tmpl
/opt/%{name}/lib/lib/catalan/templates/newclass/unittest.tmpl
/opt/%{name}/lib/lib/catalan/templates/readme.tmpl
/opt/%{name}/lib/lib/chinese/dialogues
/opt/%{name}/lib/lib/chinese/frame-labels
/opt/%{name}/lib/lib/chinese/labels
/opt/%{name}/lib/lib/chinese/moe.help
/opt/%{name}/lib/lib/chinese/templates/README
/opt/%{name}/lib/lib/chinese/templates/html.tmpl
/opt/%{name}/lib/lib/chinese/templates/method.tmpl
/opt/%{name}/lib/lib/chinese/templates/newclass/README
/opt/%{name}/lib/lib/chinese/templates/newclass/abstract.tmpl
/opt/%{name}/lib/lib/chinese/templates/newclass/enum.tmpl
/opt/%{name}/lib/lib/chinese/templates/newclass/interface.tmpl
/opt/%{name}/lib/lib/chinese/templates/newclass/stdclass.tmpl
/opt/%{name}/lib/lib/chinese/templates/newclass/unittest.tmpl
/opt/%{name}/lib/lib/chinese/templates/readme.tmpl
/opt/%{name}/lib/lib/classgraph-4.8.90.jar
/opt/%{name}/lib/lib/commons-logging-api-1.1.2.jar
/opt/%{name}/lib/lib/czech/bluejparser.help
/opt/%{name}/lib/lib/czech/dialogues
/opt/%{name}/lib/lib/czech/frame-labels
/opt/%{name}/lib/lib/czech/labels
/opt/%{name}/lib/lib/czech/moe.help
/opt/%{name}/lib/lib/czech/readme.txt
/opt/%{name}/lib/lib/czech/templates/README
/opt/%{name}/lib/lib/czech/templates/html.tmpl
/opt/%{name}/lib/lib/czech/templates/method.tmpl
/opt/%{name}/lib/lib/czech/templates/newclass/README
/opt/%{name}/lib/lib/czech/templates/newclass/abstract.tmpl
/opt/%{name}/lib/lib/czech/templates/newclass/emptyclass.tmpl
/opt/%{name}/lib/lib/czech/templates/newclass/enum.tmpl
/opt/%{name}/lib/lib/czech/templates/newclass/interface.tmpl
/opt/%{name}/lib/lib/czech/templates/newclass/mainclass.tmpl
/opt/%{name}/lib/lib/czech/templates/newclass/stdclass.tmpl
/opt/%{name}/lib/lib/czech/templates/newclass/unittest.tmpl
/opt/%{name}/lib/lib/czech/templates/readme.tmpl
/opt/%{name}/lib/lib/danish/dialogues
/opt/%{name}/lib/lib/danish/labels
/opt/%{name}/lib/lib/danish/moe.help
/opt/%{name}/lib/lib/danish/templates/README
/opt/%{name}/lib/lib/danish/templates/html.tmpl
/opt/%{name}/lib/lib/danish/templates/method.tmpl
/opt/%{name}/lib/lib/danish/templates/newclass/README
/opt/%{name}/lib/lib/danish/templates/newclass/abstract.tmpl
/opt/%{name}/lib/lib/danish/templates/newclass/enum.tmpl
/opt/%{name}/lib/lib/danish/templates/newclass/interface.tmpl
/opt/%{name}/lib/lib/danish/templates/newclass/stdclass.tmpl
/opt/%{name}/lib/lib/danish/templates/newclass/unittest.tmpl
/opt/%{name}/lib/lib/danish/templates/readme.tmpl
/opt/%{name}/lib/lib/diffutils-1.2.1.jar
/opt/%{name}/lib/lib/dutch/dialogues
/opt/%{name}/lib/lib/dutch/frame-labels
/opt/%{name}/lib/lib/dutch/labels
/opt/%{name}/lib/lib/dutch/moe.help
/opt/%{name}/lib/lib/dutch/readme.txt
/opt/%{name}/lib/lib/dutch/templates/README
/opt/%{name}/lib/lib/dutch/templates/html.tmpl
/opt/%{name}/lib/lib/dutch/templates/method.tmpl
/opt/%{name}/lib/lib/dutch/templates/newclass/README
/opt/%{name}/lib/lib/dutch/templates/newclass/abstract.tmpl
/opt/%{name}/lib/lib/dutch/templates/newclass/enum.tmpl
/opt/%{name}/lib/lib/dutch/templates/newclass/interface.tmpl
/opt/%{name}/lib/lib/dutch/templates/newclass/stdclass.tmpl
/opt/%{name}/lib/lib/dutch/templates/newclass/unittest.tmpl
/opt/%{name}/lib/lib/dutch/templates/readme.tmpl
/opt/%{name}/lib/lib/english/bluejparser.help
/opt/%{name}/lib/lib/english/dialogues
/opt/%{name}/lib/lib/english/frame-labels
/opt/%{name}/lib/lib/english/labels
/opt/%{name}/lib/lib/english/moe.help
/opt/%{name}/lib/lib/english/templates/README
/opt/%{name}/lib/lib/english/templates/method.tmpl
/opt/%{name}/lib/lib/english/templates/newclass/JavaFXclass.tmpl
/opt/%{name}/lib/lib/english/templates/newclass/README
/opt/%{name}/lib/lib/english/templates/newclass/abstract.tmpl
/opt/%{name}/lib/lib/english/templates/newclass/enum.tmpl
/opt/%{name}/lib/lib/english/templates/newclass/interface.tmpl
/opt/%{name}/lib/lib/english/templates/newclass/stdclass.tmpl
/opt/%{name}/lib/lib/english/templates/newclass/unittest.tmpl
/opt/%{name}/lib/lib/english/templates/readme.tmpl
/opt/%{name}/lib/lib/extensions2/submitter.jar
/opt/%{name}/lib/lib/fonts/RobotoMono-Bold.ttf
/opt/%{name}/lib/lib/fonts/RobotoMono-BoldItalic.ttf
/opt/%{name}/lib/lib/fonts/RobotoMono-Italic.ttf
/opt/%{name}/lib/lib/fonts/RobotoMono-Regular.ttf
/opt/%{name}/lib/lib/fonts/SourceSansPro-Bold.ttf
/opt/%{name}/lib/lib/fonts/SourceSansPro-BoldItalic.ttf
/opt/%{name}/lib/lib/fonts/SourceSansPro-Italic.ttf
/opt/%{name}/lib/lib/fonts/SourceSansPro-Regular.ttf
/opt/%{name}/lib/lib/french/dialogues
/opt/%{name}/lib/lib/french/labels
/opt/%{name}/lib/lib/french/lisezmoi
/opt/%{name}/lib/lib/french/moe.help
/opt/%{name}/lib/lib/french/templates/LisezMoi
/opt/%{name}/lib/lib/french/templates/html.tmpl
/opt/%{name}/lib/lib/french/templates/method.tmpl
/opt/%{name}/lib/lib/french/templates/newclass/LisezMoi
/opt/%{name}/lib/lib/french/templates/newclass/abstract.tmpl
/opt/%{name}/lib/lib/french/templates/newclass/enum.tmpl
/opt/%{name}/lib/lib/french/templates/newclass/interface.tmpl
/opt/%{name}/lib/lib/french/templates/newclass/stdclass.tmpl
/opt/%{name}/lib/lib/french/templates/newclass/unittest.tmpl
/opt/%{name}/lib/lib/french/templates/readme.tmpl
/opt/%{name}/lib/lib/german/dialogues
/opt/%{name}/lib/lib/german/frame-labels
/opt/%{name}/lib/lib/german/labels
/opt/%{name}/lib/lib/german/moe.help
/opt/%{name}/lib/lib/german/templates/README
/opt/%{name}/lib/lib/german/templates/html.tmpl
/opt/%{name}/lib/lib/german/templates/method.tmpl
/opt/%{name}/lib/lib/german/templates/newclass/README
/opt/%{name}/lib/lib/german/templates/newclass/abstract.tmpl
/opt/%{name}/lib/lib/german/templates/newclass/enum.tmpl
/opt/%{name}/lib/lib/german/templates/newclass/interface.tmpl
/opt/%{name}/lib/lib/german/templates/newclass/stdclass.tmpl
/opt/%{name}/lib/lib/german/templates/newclass/unittest.tmpl
/opt/%{name}/lib/lib/german/templates/readme.tmpl
/opt/%{name}/lib/lib/greek/dialogues
/opt/%{name}/lib/lib/greek/labels
/opt/%{name}/lib/lib/greek/moe.help
/opt/%{name}/lib/lib/greek/templates/README
/opt/%{name}/lib/lib/greek/templates/html.tmpl
/opt/%{name}/lib/lib/greek/templates/method.tmpl
/opt/%{name}/lib/lib/greek/templates/newclass/README
/opt/%{name}/lib/lib/greek/templates/newclass/abstract.tmpl
/opt/%{name}/lib/lib/greek/templates/newclass/enum.tmpl
/opt/%{name}/lib/lib/greek/templates/newclass/interface.tmpl
/opt/%{name}/lib/lib/greek/templates/newclass/stdclass.tmpl
/opt/%{name}/lib/lib/greek/templates/newclass/unittest.tmpl
/opt/%{name}/lib/lib/greek/templates/readme.tmpl
/opt/%{name}/lib/lib/guava-17.0.jar
/opt/%{name}/lib/lib/hamcrest-core-1.3.jar
/opt/%{name}/lib/lib/hamcrest-library-1.3.jar
/opt/%{name}/lib/lib/httpclient-4.1.1.jar
/opt/%{name}/lib/lib/httpcore-4.1.jar
/opt/%{name}/lib/lib/httpmime-4.1.1.jar
/opt/%{name}/lib/lib/images/Weather.png
/opt/%{name}/lib/lib/images/bluej-icon-256.png
/opt/%{name}/lib/lib/images/bluej-icon-32.png
/opt/%{name}/lib/lib/images/bluej-icon-48.png
/opt/%{name}/lib/lib/images/bluej-project.png
/opt/%{name}/lib/lib/images/bluej_arrow_naviview_close.gif
/opt/%{name}/lib/lib/images/bluej_arrow_naviview_open.gif
/opt/%{name}/lib/lib/images/class-icon.png
/opt/%{name}/lib/lib/images/continue.gif
/opt/%{name}/lib/lib/images/error-underline.png
/opt/%{name}/lib/lib/images/error.gif
/opt/%{name}/lib/lib/images/extmgr-info.gif
/opt/%{name}/lib/lib/images/failure.gif
/opt/%{name}/lib/lib/images/green-diagonal-4px.png
/opt/%{name}/lib/lib/images/greenfoot-icon-256.png
/opt/%{name}/lib/lib/images/greenfoot-icon-32.png
/opt/%{name}/lib/lib/images/greenfoot-icon-48.png
/opt/%{name}/lib/lib/images/greenfoot-project.png
/opt/%{name}/lib/lib/images/greenfootvm.icns
/opt/%{name}/lib/lib/images/grey-diagonal.png
/opt/%{name}/lib/lib/images/info.png
/opt/%{name}/lib/lib/images/leftarrow.gif
/opt/%{name}/lib/lib/images/me-default-icon.gif
/opt/%{name}/lib/lib/images/naviview-frame.png
/opt/%{name}/lib/lib/images/objectref.png
/opt/%{name}/lib/lib/images/objectref@2x.png
/opt/%{name}/lib/lib/images/ok.gif
/opt/%{name}/lib/lib/images/package-icon.png
/opt/%{name}/lib/lib/images/prompt-continue.gif
/opt/%{name}/lib/lib/images/prompt.gif
/opt/%{name}/lib/lib/images/readme-selected.png
/opt/%{name}/lib/lib/images/readme-selected@2x.png
/opt/%{name}/lib/lib/images/readme.png
/opt/%{name}/lib/lib/images/readme@2x.png
/opt/%{name}/lib/lib/images/red-diagonal-2px.png
/opt/%{name}/lib/lib/images/rightarrow.gif
/opt/%{name}/lib/lib/images/search.png
/opt/%{name}/lib/lib/images/small-object.gif
/opt/%{name}/lib/lib/images/step.gif
/opt/%{name}/lib/lib/images/step_into.gif
/opt/%{name}/lib/lib/images/terminate.gif
/opt/%{name}/lib/lib/images/tulip.png
/opt/%{name}/lib/lib/images/vm.icns
/opt/%{name}/lib/lib/italian/dialogues
/opt/%{name}/lib/lib/italian/frame-labels
/opt/%{name}/lib/lib/italian/labels
/opt/%{name}/lib/lib/italian/moe.help
/opt/%{name}/lib/lib/italian/templates/README
/opt/%{name}/lib/lib/italian/templates/html.tmpl
/opt/%{name}/lib/lib/italian/templates/method.tmpl
/opt/%{name}/lib/lib/italian/templates/newclass/README
/opt/%{name}/lib/lib/italian/templates/newclass/abstract.tmpl
/opt/%{name}/lib/lib/italian/templates/newclass/enum.tmpl
/opt/%{name}/lib/lib/italian/templates/newclass/interface.tmpl
/opt/%{name}/lib/lib/italian/templates/newclass/stdclass.tmpl
/opt/%{name}/lib/lib/italian/templates/newclass/unittest.tmpl
/opt/%{name}/lib/lib/italian/templates/readme.tmpl
/opt/%{name}/lib/lib/japanese/dialogues
/opt/%{name}/lib/lib/japanese/labels
/opt/%{name}/lib/lib/japanese/moe.help
/opt/%{name}/lib/lib/japanese/readme.txt
/opt/%{name}/lib/lib/japanese/templates/README
/opt/%{name}/lib/lib/japanese/templates/html.tmpl
/opt/%{name}/lib/lib/japanese/templates/method.tmpl
/opt/%{name}/lib/lib/japanese/templates/newclass/README
/opt/%{name}/lib/lib/japanese/templates/newclass/abstract.tmpl
/opt/%{name}/lib/lib/japanese/templates/newclass/enum.tmpl
/opt/%{name}/lib/lib/japanese/templates/newclass/interface.tmpl
/opt/%{name}/lib/lib/japanese/templates/newclass/stdclass.tmpl
/opt/%{name}/lib/lib/japanese/templates/newclass/unittest.tmpl
/opt/%{name}/lib/lib/japanese/templates/readme.tmpl
/opt/%{name}/lib/lib/jsch-0.1.53.jar
/opt/%{name}/lib/lib/junit-jupiter-5.5.2.jar
/opt/%{name}/lib/lib/junit-jupiter-api-5.5.2.jar
/opt/%{name}/lib/lib/junit-jupiter-engine-5.5.2.jar
/opt/%{name}/lib/lib/junit-jupiter-migrationsupport-5.5.2.jar
/opt/%{name}/lib/lib/junit-jupiter-params-5.5.2.jar
/opt/%{name}/lib/lib/junit-platform-commons-1.5.2.jar
/opt/%{name}/lib/lib/junit-platform-console-1.5.2.jar
/opt/%{name}/lib/lib/junit-platform-console-standalone-1.5.2.jar
/opt/%{name}/lib/lib/junit-platform-engine-1.5.2.jar
/opt/%{name}/lib/lib/junit-platform-launcher-1.5.2.jar
/opt/%{name}/lib/lib/junit-platform-reporting-1.5.2.jar
/opt/%{name}/lib/lib/junit-platform-runner-1.5.2.jar
/opt/%{name}/lib/lib/junit-platform-suite-api-1.5.2.jar
/opt/%{name}/lib/lib/junit-platform-testkit-1.5.2.jar
/opt/%{name}/lib/lib/junit-quickcheck-core-0.9.jar
/opt/%{name}/lib/lib/junit-vintage-engine-5.5.2.jar
/opt/%{name}/lib/lib/korean/dialogues
/opt/%{name}/lib/lib/korean/labels
/opt/%{name}/lib/lib/korean/moe.help
/opt/%{name}/lib/lib/korean/templates/README
/opt/%{name}/lib/lib/korean/templates/html.tmpl
/opt/%{name}/lib/lib/korean/templates/method.tmpl
/opt/%{name}/lib/lib/korean/templates/newclass/README
/opt/%{name}/lib/lib/korean/templates/newclass/abstract.tmpl
/opt/%{name}/lib/lib/korean/templates/newclass/enum.tmpl
/opt/%{name}/lib/lib/korean/templates/newclass/interface.tmpl
/opt/%{name}/lib/lib/korean/templates/newclass/stdclass.tmpl
/opt/%{name}/lib/lib/korean/templates/newclass/unittest.tmpl
/opt/%{name}/lib/lib/korean/templates/readme.tmpl
/opt/%{name}/lib/lib/lang-stride.jar
/opt/%{name}/lib/lib/moe.defs
/opt/%{name}/lib/lib/nsmenufx-2.1.8.jar
/opt/%{name}/lib/lib/org.eclipse.jgit-4.9.0.jar
/opt/%{name}/lib/lib/polish/frame-labels
/opt/%{name}/lib/lib/polish/templates/README
/opt/%{name}/lib/lib/polish/templates/method.tmpl
/opt/%{name}/lib/lib/polish/templates/newclass/README
/opt/%{name}/lib/lib/polish/templates/newclass/abstract.tmpl
/opt/%{name}/lib/lib/polish/templates/newclass/enum.tmpl
/opt/%{name}/lib/lib/polish/templates/newclass/interface.tmpl
/opt/%{name}/lib/lib/polish/templates/newclass/stdclass.tmpl
/opt/%{name}/lib/lib/polish/templates/newclass/unittest.tmpl
/opt/%{name}/lib/lib/polish/templates/readme.tmpl
/opt/%{name}/lib/lib/portuguese/bluejparser.help
/opt/%{name}/lib/lib/portuguese/dialogues
/opt/%{name}/lib/lib/portuguese/frame-labels
/opt/%{name}/lib/lib/portuguese/labels
/opt/%{name}/lib/lib/portuguese/moe.help
/opt/%{name}/lib/lib/portuguese/templates/README
/opt/%{name}/lib/lib/portuguese/templates/html.tmpl
/opt/%{name}/lib/lib/portuguese/templates/method.tmpl
/opt/%{name}/lib/lib/portuguese/templates/newclass/JavaFXclass.tmpl
/opt/%{name}/lib/lib/portuguese/templates/newclass/README
/opt/%{name}/lib/lib/portuguese/templates/newclass/abstract.tmpl
/opt/%{name}/lib/lib/portuguese/templates/newclass/enum.tmpl
/opt/%{name}/lib/lib/portuguese/templates/newclass/interface.tmpl
/opt/%{name}/lib/lib/portuguese/templates/newclass/stdclass.tmpl
/opt/%{name}/lib/lib/portuguese/templates/newclass/unittest.tmpl
/opt/%{name}/lib/lib/portuguese/templates/readme.tmpl
/opt/%{name}/lib/lib/russian/dialogues
/opt/%{name}/lib/lib/russian/labels
/opt/%{name}/lib/lib/russian/moe.help
/opt/%{name}/lib/lib/russian/readme.txt
/opt/%{name}/lib/lib/russian/templates/README
/opt/%{name}/lib/lib/russian/templates/html.tmpl
/opt/%{name}/lib/lib/russian/templates/method.tmpl
/opt/%{name}/lib/lib/russian/templates/newclass/README
/opt/%{name}/lib/lib/russian/templates/newclass/abstract.tmpl
/opt/%{name}/lib/lib/russian/templates/newclass/enum.tmpl
/opt/%{name}/lib/lib/russian/templates/newclass/interface.tmpl
/opt/%{name}/lib/lib/russian/templates/newclass/stdclass.tmpl
/opt/%{name}/lib/lib/russian/templates/newclass/unittest.tmpl
/opt/%{name}/lib/lib/russian/templates/readme.tmpl
/opt/%{name}/lib/lib/slf4j-api-1.7.2.jar
/opt/%{name}/lib/lib/slf4j-jdk14-1.7.2.jar
/opt/%{name}/lib/lib/slovak/bluejparser.help
/opt/%{name}/lib/lib/slovak/dialogues
/opt/%{name}/lib/lib/slovak/frame-labels
/opt/%{name}/lib/lib/slovak/labels
/opt/%{name}/lib/lib/slovak/moe.help
/opt/%{name}/lib/lib/slovak/readme.txt
/opt/%{name}/lib/lib/slovak/templates/README
/opt/%{name}/lib/lib/slovak/templates/method.tmpl
/opt/%{name}/lib/lib/slovak/templates/newclass/README
/opt/%{name}/lib/lib/slovak/templates/newclass/abstract.tmpl
/opt/%{name}/lib/lib/slovak/templates/newclass/emptyclass.tmpl
/opt/%{name}/lib/lib/slovak/templates/newclass/enum.tmpl
/opt/%{name}/lib/lib/slovak/templates/newclass/interface.tmpl
/opt/%{name}/lib/lib/slovak/templates/newclass/mainclass.tmpl
/opt/%{name}/lib/lib/slovak/templates/newclass/stdclass.tmpl
/opt/%{name}/lib/lib/slovak/templates/newclass/unittest.tmpl
/opt/%{name}/lib/lib/slovak/templates/readme.tmpl
/opt/%{name}/lib/lib/spanish/dialogues
/opt/%{name}/lib/lib/spanish/labels
/opt/%{name}/lib/lib/spanish/moe.help
/opt/%{name}/lib/lib/spanish/templates/README
/opt/%{name}/lib/lib/spanish/templates/html.tmpl
/opt/%{name}/lib/lib/spanish/templates/method.tmpl
/opt/%{name}/lib/lib/spanish/templates/newclass/README
/opt/%{name}/lib/lib/spanish/templates/newclass/abstract.tmpl
/opt/%{name}/lib/lib/spanish/templates/newclass/enum.tmpl
/opt/%{name}/lib/lib/spanish/templates/newclass/interface.tmpl
/opt/%{name}/lib/lib/spanish/templates/newclass/stdclass.tmpl
/opt/%{name}/lib/lib/spanish/templates/newclass/unittest.tmpl
/opt/%{name}/lib/lib/spanish/templates/readme.tmpl
/opt/%{name}/lib/lib/stylesheets/debugger.css
/opt/%{name}/lib/lib/stylesheets/dialogs.css
/opt/%{name}/lib/lib/stylesheets/editor-banners.css
/opt/%{name}/lib/lib/stylesheets/editor-catalogue.css
/opt/%{name}/lib/lib/stylesheets/editor-error-bar.css
/opt/%{name}/lib/lib/stylesheets/editor-error-fix.css
/opt/%{name}/lib/lib/stylesheets/editor-expression.css
/opt/%{name}/lib/lib/stylesheets/editor-help.css
/opt/%{name}/lib/lib/stylesheets/editor-menu.css
/opt/%{name}/lib/lib/stylesheets/editor-selection.css
/opt/%{name}/lib/lib/stylesheets/editor-slot-choice.css
/opt/%{name}/lib/lib/stylesheets/editor-suggestions.css
/opt/%{name}/lib/lib/stylesheets/editor-tabs.css
/opt/%{name}/lib/lib/stylesheets/flow.css
/opt/%{name}/lib/lib/stylesheets/frame-style.css
/opt/%{name}/lib/lib/stylesheets/inspectors.css
/opt/%{name}/lib/lib/stylesheets/java-colors.css
/opt/%{name}/lib/lib/stylesheets/moe.css
/opt/%{name}/lib/lib/stylesheets/pkgmgrframe.css
/opt/%{name}/lib/lib/stylesheets/popup.css
/opt/%{name}/lib/lib/stylesheets/shared.css
/opt/%{name}/lib/lib/stylesheets/terminal.css
/opt/%{name}/lib/lib/stylesheets/tests.css
/opt/%{name}/lib/lib/swedish/dialogues
/opt/%{name}/lib/lib/swedish/labels
/opt/%{name}/lib/lib/swedish/moe.help
/opt/%{name}/lib/lib/swedish/templates/README
/opt/%{name}/lib/lib/swedish/templates/html.tmpl
/opt/%{name}/lib/lib/swedish/templates/method.tmpl
/opt/%{name}/lib/lib/swedish/templates/newclass/README
/opt/%{name}/lib/lib/swedish/templates/newclass/abstract.tmpl
/opt/%{name}/lib/lib/swedish/templates/newclass/enum.tmpl
/opt/%{name}/lib/lib/swedish/templates/newclass/interface.tmpl
/opt/%{name}/lib/lib/swedish/templates/newclass/stdclass.tmpl
/opt/%{name}/lib/lib/swedish/templates/newclass/unittest.tmpl
/opt/%{name}/lib/lib/swedish/templates/readme.tmpl
/opt/%{name}/lib/lib/tutorial/Cat.class
/opt/%{name}/lib/lib/tutorial/Cat.java
/opt/%{name}/lib/lib/tutorial/CatView.class
/opt/%{name}/lib/lib/tutorial/CatView.java
/opt/%{name}/lib/lib/tutorial/cat1.jpg
/opt/%{name}/lib/lib/tutorial/cat2.jpg
/opt/%{name}/lib/lib/tutorial/cat3.jpg
/opt/%{name}/lib/lib/tutorial/htmlsrc/bluej-icon-256.png
/opt/%{name}/lib/lib/tutorial/htmlsrc/tutorial.css
/opt/%{name}/lib/lib/tutorial/package.bluej
/opt/%{name}/lib/lib/tutorial/part1.html
/opt/%{name}/lib/lib/tutorial/part2.html
/opt/%{name}/lib/lib/tutorial/part3.html
/opt/%{name}/lib/lib/tutorial/part4.html
/opt/%{name}/lib/lib/tutorial/part5.html
/opt/%{name}/lib/lib/tutorial/part6.html
/opt/%{name}/lib/lib/tutorial/part7.html
/opt/%{name}/lib/lib/tutorial/part8.html
/opt/%{name}/lib/lib/tutorial/tutorial.html
/opt/%{name}/lib/lib/userlib/README.TXT
/opt/%{name}/lib/lib/wellbehavedfx-0.3.3.jar
/opt/%{name}/lib/lib/windowtofront.js
/opt/%{name}/lib/lib/xom-1.2.9.jar
/usr/share/applications/bluej.desktop

%changelog
* Sat Jul 23 2022 jehaj <kagenogmig@gmail.com> - 5.0.3
- Initial build to COPR
